# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Austen Madden
footer_title: Contact Info
greeting: Welcome!
email: maddenausten@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a software developer from Columbus, Ohio interested in just a bit of
  everything.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://austenmadden.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: aus10madden
github_username:  austenmadden
linkedin_username: austenmadden
disqus:
    shortname: austenmadden-me

# Build settings
markdown: kramdown
theme: sanguine
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
